# Generated by Django 5.2.1 on 2025-05-14 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Şirket Adı")),
                (
                    "code",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Şirket Kodu"
                    ),
                ),
                (
                    "user_limit",
                    models.IntegerField(default=0, verbose_name="Kullanıcı Limiti"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Kullanma Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Şirket",
                "verbose_name_plural": "Şirketler",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InsuranceCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Sigorta Şirketi Adı"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="insurance_company_logos/",
                        verbose_name="Sigorta Şirketi Logosu",
                    ),
                ),
                (
                    "login_url",
                    models.CharField(max_length=255, verbose_name="Giriş URL"),
                ),
                (
                    "explorer_url",
                    models.CharField(max_length=255, verbose_name="Explorer URL"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Sigorta Şirketi Kodu"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
            ],
            options={
                "verbose_name": "Sigorta Şirketi",
                "verbose_name_plural": "Sigorta Şirketleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompanyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Kullanma Tarihi"
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="Admin mi?"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Şirket Kullanıcısı",
                "verbose_name_plural": "Şirket Kullanıcıları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InsuranceCompanyItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sms_code", models.CharField(max_length=255, verbose_name="SMS Kodu")),
                (
                    "totp_code",
                    models.CharField(max_length=255, verbose_name="Totp Kodu"),
                ),
                (
                    "proxy_url",
                    models.CharField(max_length=255, verbose_name="Proxy URL"),
                ),
                (
                    "proxy_username",
                    models.CharField(
                        max_length=255, verbose_name="Proxy Kullanıcı Adı"
                    ),
                ),
                (
                    "proxy_password",
                    models.CharField(max_length=255, verbose_name="Proxy Şifre"),
                ),
                (
                    "is_proxy_active",
                    models.BooleanField(default=True, verbose_name="Proxy Aktif mi?"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "is_car_query",
                    models.BooleanField(default=False, verbose_name="Araç Sorgulama"),
                ),
                (
                    "cookie_use",
                    models.BooleanField(default=False, verbose_name="Cookie Kullanımı"),
                ),
                (
                    "cookie",
                    models.TextField(blank=True, null=True, verbose_name="Cookie"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "insurance_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.insurancecompany",
                        verbose_name="Sigorta Şirketi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sigorta Şirketi Öğesi",
                "verbose_name_plural": "Sigorta Şirketi Öğeleri",
                "ordering": ["-created_at"],
            },
        ),
    ]
