# Generated by Django 5.2.1 on 2025-05-14 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueryType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("traffic", "Trafik Sigortası"),
                            ("casco", "Kasko"),
                            ("health", "Sağlık Sigortası"),
                            ("life", "Hayat Sigortası"),
                            ("travel", "Seyahat Sigortası"),
                            ("home", "Konut Sigortası"),
                            ("workplace", "İşyeri Sigortası"),
                            ("other", "Diğer"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Sorgu Türü",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
            ],
            options={
                "verbose_name": "Sorgu Türü",
                "verbose_name_plural": "Sorgu Türleri",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Rol Adı")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roller",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="insurancecompanyitem",
            name="query_types",
            field=models.ManyToManyField(
                blank=True, to="api.querytype", verbose_name="Sorgu Türleri"
            ),
        ),
        migrations.AddField(
            model_name="companyuser",
            name="roles",
            field=models.ManyToManyField(
                blank=True, to="api.role", verbose_name="Roller"
            ),
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_query",
                    models.BooleanField(default=True, verbose_name="Sorgulama Yetkisi"),
                ),
                (
                    "can_create",
                    models.BooleanField(
                        default=False, verbose_name="Oluşturma Yetkisi"
                    ),
                ),
                (
                    "can_update",
                    models.BooleanField(
                        default=False, verbose_name="Güncelleme Yetkisi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "query_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.querytype",
                        verbose_name="Sorgu Türü",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="api.role",
                        verbose_name="Rol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol İzni",
                "verbose_name_plural": "Rol İzinleri",
                "unique_together": {("role", "query_type")},
            },
        ),
    ]
