# Generated by Django 5.2.1 on 2025-05-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_querytype_role_insurancecompanyitem_query_types_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurancecompanyitem",
            name="phone_number",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Telefon Numarası"
            ),
            preserve_default=False,
        ),
    ]
