# Generated by Django 5.2.1 on 2025-05-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_insurancecompanyitem_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Partage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Partaj Adı")),
                (
                    "code",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Partaj Kodu"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
            ],
            options={
                "verbose_name": "Partaj",
                "verbose_name_plural": "Partajlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="insurancecompanyitem",
            name="partage",
            field=models.ManyToManyField(
                blank=True, to="api.partage", verbose_name="Partajlar"
            ),
        ),
    ]
