# Generated by Django 5.2.1 on 2025-05-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_partage_insurancecompanyitem_partage"),
    ]

    operations = [
        migrations.AddField(
            model_name="partage",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Sıra"),
        ),
    ]
