# Generated by Django 5.2.1 on 2025-05-15 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_partage_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="insurancecompanyitem",
            name="partage",
        ),
        migrations.AddField(
            model_name="insurancecompanyitem",
            name="partage",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.partage",
                verbose_name="Partaj",
            ),
            preserve_default=False,
        ),
    ]
