# Generated by Django 5.2.1 on 2025-05-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_insurancecompanyitem_partage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurancecompanyitem",
            name="password",
            field=models.CharField(default=1, max_length=255, verbose_name="Şifre"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="insurancecompanyitem",
            name="username",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Kullanıcı Adı"
            ),
            preserve_default=False,
        ),
    ]
